### ISSUE TITLE
Have fun in playground

### ISSUE THREAD

**Issue by estelmus** [b00tc4mp/isdi-bootcamp-202402#133]
**Tasks Feb 6th 2024**
- [x] Create a pix with pixel art (playing with relative and absolute positioning in HTML ) --> VSCode. 
- [x] Create a car with pixel art (idem) 
- [x] Create an octopus with pixel art (idem)
- [x] Create a freestyle one item (idem)
- [ ] animate pig eyes to roll 🙄🙄
* only use relative and absolute positions, not flex...

**Tasks Feb 7th 2024**
- [x] SASSify all
- [x] Create building: 10 floors, 5 windows per floor, 1 main center entrance (use flex).
- [ ] Add textures to the building, (entrance picture, window frames, window frames) make it nice! 
- [x] Mount a mondarioan (use flex https://lgivaud.files.wordpress.com/2015/04/cuadros-mondrian-arte-abstracto-20x20-decoracion-mondrian-11934-mla20052593222_022014-f.jpg?w=640)

**Tasks Feb 9th** 
- [ ] Mount a "mondorian" (use grid template -columns and rows (use flex https://lgivaud.files.wordpress.com/2015/04/cuadros-mondrian-arte-abstracto-20x20-decoracion-mondrian-11934-mla20052593222_022014-f.jpg?w=640)

**👀 HINTS 👀**
https://getbem.com/
https://keepinguptodate.com/pages/2020/05/bem-visually-explained/ 
https://keepinguptodate.com/pages/2020/05/05-bem-naming-structure.svg

**Comment by estelmora** [comment]
* pig done!

**Comment by estelmora** [comment]
* pig done!
* car done!

**Comment by estelmora** [comment]
Create a pix with pixel art ✅

**Comment by estelmora** [comment]
Create a car pixel art ✅

**Comment by estelmora** [comment]
Create a horse with pixel art  ✅

**Comment by estelmora** [comment]
Create an octopus with pixel art ✅

**Comment by estelmora** [comment]
Create a freestyle w pixar art ✅ -sun
